import { Conference } from "./types";

export const CONFERENCES: Conference[] = [
  {
    id: "money2020-usa-2026",
    name: "Money20/20 USA",
    startDate: "2026-10-25",
    endDate: "2026-10-28",
    city: "Las Vegas",
    country: "USA",
    region: "NA",
    verticals: ["payments", "fintech", "treasury", "fx"],
    estAudienceSize: 12000,
    website: "https://www.money2020.com/",
  },
  {
    id: "money2020-europe-2026",
    name: "Money20/20 Europe",
    startDate: "2026-06-02",
    endDate: "2026-06-04",
    city: "Amsterdam",
    country: "Netherlands",
    region: "EUROPE",
    verticals: ["payments", "fintech", "treasury", "fx"],
    estAudienceSize: 8000,
    website: "https://www.money2020.com/",
  },
  {
    id: "sibos-2026",
    name: "Sibos",
    startDate: "2026-09-14",
    endDate: "2026-09-17",
    city: "Singapore",
    country: "Singapore",
    region: "APAC",
    verticals: ["payments", "treasury", "fx", "fintech"],
    estAudienceSize: 9000,
    website: "https://www.sibos.com/",
  },
  {
    id: "finovatefall-2026",
    name: "FinovateFall",
    startDate: "2026-09-21",
    endDate: "2026-09-23",
    city: "New York",
    country: "USA",
    region: "NA",
    verticals: ["fintech", "payments"],
    estAudienceSize: 1500,
    website: "https://finovate.com/",
  },
  {
    id: "mif-2026",
    name: "Merchant Innovators Forum",
    startDate: "2026-04-28",
    endDate: "2026-04-29",
    city: "London",
    country: "UK",
    region: "EUROPE",
    verticals: ["payments", "fintech"],
    estAudienceSize: 600,
  },
  {
    id: "itb-berlin-2026",
    name: "ITB Berlin",
    startDate: "2026-03-03",
    endDate: "2026-03-05",
    city: "Berlin",
    country: "Germany",
    region: "EUROPE",
    verticals: ["travel"],
    estAudienceSize: 90000,
    website: "https://www.itb.com/",
  },
  {
    id: "phocuswright-europe-2026",
    name: "Phocuswright Europe",
    startDate: "2026-06-09",
    endDate: "2026-06-11",
    city: "Barcelona",
    country: "Spain",
    region: "EUROPE",
    verticals: ["travel", "payments", "fintech"],
    estAudienceSize: 800,
    website: "https://www.phocuswright.com/",
  },
  {
    id: "gbta-2026",
    name: "GBTA Convention",
    startDate: "2026-07-18",
    endDate: "2026-07-22",
    city: "Chicago",
    country: "USA",
    region: "NA",
    verticals: ["travel"],
    estAudienceSize: 7000,
    website: "https://www.gbta.org/",
  },
  {
    id: "seamless-middleeast-2026",
    name: "Seamless Middle East",
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    city: "Dubai",
    country: "UAE",
    region: "MIDDLE_EAST",
    verticals: ["payments", "fintech"],
    estAudienceSize: 20000,
    website: "https://www.seamless.com/",
  },
  {
    id: "afp-2026",
    name: "AFP Treasury Management Conference",
    startDate: "2026-10-18",
    endDate: "2026-10-21",
    city: "San Diego",
    country: "USA",
    region: "NA",
    verticals: ["treasury", "fx"],
    estAudienceSize: 7000,
    website: "https://www.afponline.org/",
  },
  {
    id: "eurofinance-2026",
    name: "EuroFinance International Treasury Management",
    startDate: "2026-09-29",
    endDate: "2026-10-01",
    city: "Vienna",
    country: "Austria",
    region: "EUROPE",
    verticals: ["treasury", "fx"],
    estAudienceSize: 3000,
    website: "https://www.eurofinance.com/",
  },
  {
    id: "token2049-sg-2026",
    name: "TOKEN2049 Singapore",
    startDate: "2026-09-23",
    endDate: "2026-09-24",
    city: "Singapore",
    country: "Singapore",
    region: "APAC",
    verticals: ["fintech", "other"],
    estAudienceSize: 15000,
    website: "https://www.token2049.com/",
  },
  {
    id: "websummit-2026",
    name: "Web Summit",
    startDate: "2026-11-02",
    endDate: "2026-11-05",
    city: "Lisbon",
    country: "Portugal",
    region: "EUROPE",
    verticals: ["saas", "developer", "fintech"],
    estAudienceSize: 70000,
    website: "https://websummit.com/",
  },
  {
    id: "collision-2026",
    name: "Collision",
    startDate: "2026-06-22",
    endDate: "2026-06-25",
    city: "Toronto",
    country: "Canada",
    region: "NA",
    verticals: ["saas", "developer", "fintech"],
    estAudienceSize: 30000,
    website: "https://collisionconf.com/",
  },
  {
    id: "techcrunch-disrupt-2026",
    name: "TechCrunch Disrupt",
    startDate: "2026-09-15",
    endDate: "2026-09-17",
    city: "San Francisco",
    country: "USA",
    region: "NA",
    verticals: ["saas", "developer", "fintech"],
    estAudienceSize: 10000,
    website: "https://techcrunch.com/events/",
  },
  {
    id: "innovatefinance-gif-2026",
    name: "Innovate Finance Global Summit (IFGS)",
    startDate: "2026-04-20",
    endDate: "2026-04-21",
    city: "London",
    country: "UK",
    region: "EUROPE",
    verticals: ["fintech", "payments"],
    estAudienceSize: 2000,
    website: "https://www.innovatefinance.com/",
  },
  {
    id: "fintechweek-london-2026",
    name: "FinTech Week London",
    startDate: "2026-07-06",
    endDate: "2026-07-10",
    city: "London",
    country: "UK",
    region: "EUROPE",
    verticals: ["fintech", "payments"],
    estAudienceSize: 5000,
  },
  {
    id: "pay360-2026",
    name: "PAY360",
    startDate: "2026-03-25",
    endDate: "2026-03-26",
    city: "London",
    country: "UK",
    region: "EUROPE",
    verticals: ["payments"],
    estAudienceSize: 3000,
    website: "https://www.pay360event.com/",
  },
  {
    id: "moneyconf-israel-2026",
    name: "MoneyTech / FinTech Conference (Israel)",
    startDate: "2026-12-08",
    endDate: "2026-12-08",
    city: "Tel Aviv",
    country: "Israel",
    region: "MIDDLE_EAST",
    verticals: ["fintech", "payments"],
    estAudienceSize: 800,
  },
  {
    id: "rise-hk-2026",
    name: "RISE",
    startDate: "2026-07-07",
    endDate: "2026-07-09",
    city: "Hong Kong",
    country: "Hong Kong",
    region: "APAC",
    verticals: ["fintech", "saas"],
    estAudienceSize: 15000,
    website: "https://riseconf.com/",
  },
  {
    id: "africa-fintech-summit-2026",
    name: "Africa Fintech Summit",
    startDate: "2026-11-18",
    endDate: "2026-11-19",
    city: "Cape Town",
    country: "South Africa",
    region: "AFRICA",
    verticals: ["fintech", "payments"],
    estAudienceSize: 1200,
  },
];

